export const TIME_LIST = {
    'week': '一周',
    'month': '一月',
    'today': '今日',
    'history': '历史'
}

export const SCENE_CATEGORY = {
    'visit': {
        tt: '访问次数',
        tt2: '占所有景点访问次数比例',
        c1: '热门景点访问次数占所有访问人次比例',
        c2: '热门景点访问人次数'
    },
    'interest': {
        tt: '感兴趣人数',
        tt2: '占所有网站注册用户比例',
        c1: '热门景点感兴趣人数占所有注册用户比例',
        c2: '热门景点感兴趣用户人数'
    },
    'comment': {
        tt: '评论次数',
        tt2: '占所有游记评论次数比例',
        c1: '热门景点评论次数占所有游记评论次数比例',
        c2: '热门景点游记评论数量'
    }
}

export const HOTEL_CATEGORY = {
    'visit': {
        tt: '访问次数',
        tt2: '与昨日相比',
        c1: '热门景点访问次数占所有访问人次比例',
        c2: '热门景点访问人次数'
    },
    'interest': {
        tt: '感兴趣人数',
        tt2: '占所有网站注册用户比例',
        c1: '热门景点感兴趣人数占所有注册用户比例',
        c2: '热门景点感兴趣用户人数'
    },
    'comment': {
        tt: '评论次数',
        tt2: '占所有游记评论次数比例',
        c1: '热门景点评论次数占所有游记评论次数比例',
        c2: '热门景点游记评论数量'
    }
}


export const coachCityList = [
    '杭州',
    '宁波',
    '温州',
    '嘉兴',
    '湖州',
    '绍兴',
    '金华',
    '衢州',
    '舟山',
    '台州',
    '丽水',
    '上海'
]

export const TRAIN_TYPES = {
    D: '动车',
    Z: '直达',
    T: '特快',
    G: '高铁',
    K: '快速',
    T: '特快'
}
export const trains = [{
    "trainno": "G45",
    "type": "G",
    "typename": "高铁",
    "station": "北京南",
    "endstation": "杭州东",
    "departuretime": "15:25",
    "arrivaltime": "21:23",
    "costtime": "5小时58分",
    "trainno12306": "",
    "distance": 1279,
    "day": 1,
    "isend": 0,
    "sequenceno": 1,
    "priceed": 538.5,
    "priceyd": 907,
    "pricesw": 1701,
    "pricetd": "-",
    "pricerz": "-",
    "priceyz": "-",
    "pricegr1": "-",
    "pricegr2": "-",
    "pricerw1": "-",
    "pricerw2": "-",
    "priceyw1": "-",
    "priceyw2": "-",
    "priceyw3": "-",
    "pricewz": "-",
    "priceqt": "-",
    "pricedw": "-",
    "pricedw1": "-"
},
{
    "trainno": "G37",
    "type": "G",
    "typename": "高铁",
    "station": "北京南",
    "endstation": "杭州东",
    "departuretime": "16:05",
    "arrivaltime": "22:07",
    "costtime": "6小时2分",
    "trainno12306": "",
    "distance": 1279,
    "day": 1,
    "isend": 1,
    "sequenceno": 1,
    "priceed": 538.5,
    "priceyd": 907,
    "pricesw": 1701,
    "pricetd": "-",
    "pricerz": "-",
    "priceyz": "-",
    "pricegr1": "-",
    "pricegr2": "-",
    "pricerw1": "-",
    "pricerw2": "-",
    "priceyw1": "-",
    "priceyw2": "-",
    "priceyw3": "-",
    "pricewz": "-",
    "priceqt": "-",
    "pricedw": "-",
    "pricedw1": "-"
},
{
    "trainno": "Z281",
    "type": "Z",
    "typename": "直达特快",
    "station": "北京",
    "endstation": "杭州",
    "departuretime": "19:10",
    "arrivaltime": "12:23",
    "costtime": "17小时13分",
    "trainno12306": "",
    "distance": 1616,
    "day": 2,
    "isend": 1,
    "sequenceno": 8,
    "priceyz": 192,
    "priceyw1": 328,
    "pricerw1": 515,
    "pricesw": "-",
    "pricetd": "-",
    "pricerz": "-",
    "pricegr1": "-",
    "pricegr2": "-",
    "pricerw2": "-",
    "priceyw2": "-",
    "priceyw3": "-",
    "priceyd": "-",
    "priceed": "-",
    "pricewz": "-",
    "priceqt": "-",
    "pricedw": "-",
    "pricedw1": "-"
},
{
    "trainno": "D717",
    "type": "D",
    "typename": "动车",
    "station": "北京",
    "endstation": "杭州",
    "departuretime": "19:16",
    "arrivaltime": "08:47",
    "costtime": "13小时31分",
    "trainno12306": "",
    "distance": 1633,
    "day": 2,
    "isend": 1,
    "sequenceno": 1,
    "priceed": 302,
    "priceyw1": 454,
    "pricerw1": 574,
    "pricesw": "-",
    "pricetd": "-",
    "pricerz": "-",
    "priceyz": "-",
    "pricegr1": "-",
    "pricegr2": "-",
    "pricerw2": "-",
    "priceyw2": "-",
    "priceyw3": "-",
    "priceyd": "-",
    "pricewz": "-",
    "priceqt": "-",
    "pricedw": "-",
    "pricedw1": "-"
},
{
    "trainno": "K101",
    "type": "K",
    "typename": "快速",
    "station": "北京",
    "endstation": "杭州",
    "departuretime": "23:20",
    "arrivaltime": "20:24",
    "costtime": "21小时4分",
    "trainno12306": "",
    "distance": 1633,
    "day": 2,
    "isend": 0,
    "sequenceno": 1,
    "priceyz": 189.5,
    "priceyw1": 322.5,
    "pricerw1": 504.5,
    "pricesw": "-",
    "pricetd": "-",
    "pricerz": "-",
    "pricegr1": "-",
    "pricegr2": "-",
    "pricerw2": "-",
    "priceyw2": "-",
    "priceyw3": "-",
    "priceyd": "-",
    "priceed": "-",
    "pricewz": "-",
    "priceqt": "-",
    "pricedw": "-",
    "pricedw1": "-"
}
]

export const flights = [{
    "airlineCompany": "中国南方航空股份有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 11:10:00",
    "tkTime": "2020-05-28 08:00:00",
    "lowestPriceInfo": {
        "discount": 6.1,
        "price": 1550,
        "standardPrice": 2540,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "CZ3101",
    "onTimeRate": 100,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "中国南方航空股份有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 12:10:00",
    "tkTime": "2020-05-28 09:00:00",
    "lowestPriceInfo": {
        "discount": 7,
        "price": 1790,
        "standardPrice": 2540,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "CZ3099",
    "onTimeRate": 100,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "中国南方航空股份有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 12:30:00",
    "tkTime": "2020-05-28 09:20:00",
    "lowestPriceInfo": {
        "discount": 6.1,
        "price": 1550,
        "standardPrice": 2540,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "CZ5414",
    "onTimeRate": 0,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "中国国际航空股份有限公司",
    "leaveBuilding": "T1航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 12:45:00",
    "tkTime": "2020-05-28 09:35:00",
    "lowestPriceInfo": {
        "discount": 5.4,
        "price": 1360,
        "standardPrice": 2540,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "CA1380",
    "onTimeRate": 96.67,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T3航站楼"
},
{
    "airlineCompany": "中国南方航空股份有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 13:10:00",
    "tkTime": "2020-05-28 10:00:00",
    "lowestPriceInfo": {
        "discount": 6.1,
        "price": 1550,
        "standardPrice": 2540,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "CZ3121",
    "onTimeRate": 96.67,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "中国东方航空股份有限公司",
    "leaveBuilding": "T1航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 14:55:00",
    "tkTime": "2020-05-28 11:50:00",
    "lowestPriceInfo": {
        "discount": 7,
        "price": 1615,
        "standardPrice": 2310,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "MU5182",
    "onTimeRate": 100,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "中国南方航空股份有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 15:05:00",
    "tkTime": "2020-05-28 12:00:00",
    "lowestPriceInfo": {
        "discount": 6.1,
        "price": 1550,
        "standardPrice": 2540,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "CZ3103",
    "onTimeRate": 96.67,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "厦门航空有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 15:25:00",
    "tkTime": "2020-05-28 12:35:00",
    "lowestPriceInfo": {
        "discount": 5.1,
        "price": 1300,
        "standardPrice": 2540,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "MF8188",
    "onTimeRate": 0,
    "arrivePort": "大兴国际机场",
    "arriveBuilding": "航站楼"
},
{
    "airlineCompany": "中国南方航空股份有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 15:25:00",
    "tkTime": "2020-05-28 12:35:00",
    "lowestPriceInfo": {
        "discount": 5.4,
        "price": 1370,
        "standardPrice": 2540,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "CZ5024",
    "onTimeRate": 0,
    "arrivePort": "大兴国际机场",
    "arriveBuilding": "航站楼"
},
{
    "airlineCompany": "海南航空股份有限公司",
    "leaveBuilding": "T1航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 16:05:00",
    "tkTime": "2020-05-28 12:55:00",
    "lowestPriceInfo": {
        "discount": 4.8,
        "price": 1110,
        "standardPrice": 2310,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "HU7806",
    "onTimeRate": 96.67,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "中国国际航空股份有限公司",
    "leaveBuilding": "T1航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 16:50:00",
    "tkTime": "2020-05-28 13:40:00",
    "lowestPriceInfo": {
        "discount": 5.4,
        "price": 1360,
        "standardPrice": 2540,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "CA1322",
    "onTimeRate": 96.67,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T3航站楼"
},
{
    "airlineCompany": "中国南方航空股份有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 17:10:00",
    "tkTime": "2020-05-28 14:00:00",
    "lowestPriceInfo": {
        "discount": 6.1,
        "price": 1550,
        "standardPrice": 2540,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "CZ3109",
    "onTimeRate": 100,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "中国国际航空股份有限公司",
    "leaveBuilding": "T1航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 18:50:00",
    "tkTime": "2020-05-28 15:40:00",
    "lowestPriceInfo": {
        "discount": 5.4,
        "price": 1360,
        "standardPrice": 2540,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "CA1316",
    "onTimeRate": 93.33,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T3航站楼"
},
{
    "airlineCompany": "中国南方航空股份有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 19:10:00",
    "tkTime": "2020-05-28 16:00:00",
    "lowestPriceInfo": {
        "discount": 6.1,
        "price": 1550,
        "standardPrice": 2540,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "CZ3115",
    "onTimeRate": 100,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "海南航空股份有限公司",
    "leaveBuilding": "T1航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 20:20:00",
    "tkTime": "2020-05-28 17:00:00",
    "lowestPriceInfo": {
        "discount": 5.4,
        "price": 1240,
        "standardPrice": 2310,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "HU7808",
    "onTimeRate": 93.33,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "中国国际航空股份有限公司",
    "leaveBuilding": "T1航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 21:50:00",
    "tkTime": "2020-05-28 18:40:00",
    "lowestPriceInfo": {
        "discount": 5.2,
        "price": 1330,
        "standardPrice": 2540,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "CA1328",
    "onTimeRate": 90,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T3航站楼"
},
{
    "airlineCompany": "中国国际航空股份有限公司",
    "leaveBuilding": "T1航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 23:00:00",
    "tkTime": "2020-05-28 19:40:00",
    "lowestPriceInfo": {
        "discount": 5.1,
        "price": 1300,
        "standardPrice": 2540,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "CA1302",
    "onTimeRate": 93.33,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T3航站楼"
},
{
    "airlineCompany": "中国东方航空股份有限公司",
    "leaveBuilding": "T1航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 23:55:00",
    "tkTime": "2020-05-28 20:50:00",
    "lowestPriceInfo": {
        "discount": 7,
        "price": 1615,
        "standardPrice": 2310,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "MU5282",
    "onTimeRate": 86.67,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "中国联合航空有限公司",
    "leaveBuilding": "T1航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-29 00:50:00",
    "tkTime": "2020-05-28 21:50:00",
    "lowestPriceInfo": {
        "discount": 4.8,
        "price": 1106,
        "standardPrice": 2310,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "KN5900",
    "onTimeRate": 100,
    "arrivePort": "大兴国际机场",
    "arriveBuilding": "航站楼"
},
{
    "airlineCompany": "厦门航空有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 11:10:00",
    "tkTime": "2020-05-28 08:00:00",
    "lowestPriceInfo": {
        "discount": 6.4,
        "price": 1630,
        "standardPrice": 1630,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "MF1003",
    "onTimeRate": 100,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "厦门航空有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 12:10:00",
    "tkTime": "2020-05-28 09:00:00",
    "lowestPriceInfo": {
        "discount": 7.4,
        "price": 1880,
        "standardPrice": 1880,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "MF1001",
    "onTimeRate": 100,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "厦门航空有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 13:10:00",
    "tkTime": "2020-05-28 10:00:00",
    "lowestPriceInfo": {
        "discount": 6.4,
        "price": 1630,
        "standardPrice": 1630,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "MF1023",
    "onTimeRate": 96.67,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "厦门航空有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 15:05:00",
    "tkTime": "2020-05-28 12:00:00",
    "lowestPriceInfo": {
        "discount": 6.4,
        "price": 1630,
        "standardPrice": 1630,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "MF1005",
    "onTimeRate": 96.67,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "厦门航空有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 17:10:00",
    "tkTime": "2020-05-28 14:00:00",
    "lowestPriceInfo": {
        "discount": 6.4,
        "price": 1630,
        "standardPrice": 1630,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "MF1011",
    "onTimeRate": 100,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "厦门航空有限公司",
    "leaveBuilding": "T2航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 19:10:00",
    "tkTime": "2020-05-28 16:00:00",
    "lowestPriceInfo": {
        "discount": 6.4,
        "price": 1630,
        "standardPrice": 1630,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "MF1017",
    "onTimeRate": 100,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
},
{
    "airlineCompany": "海南航空股份有限公司",
    "leaveBuilding": "T1航站楼",
    "transferList": [],
    "leavePort": "新白云国际机场",
    "arTime": "2020-05-28 11:00:00",
    "tkTime": "2020-05-28 08:00:00",
    "lowestPriceInfo": {
        "discount": 5.4,
        "price": 1250,
        "standardPrice": 2310,
        "oilFee": 0,
        "buildTax": 50
    },
    "arriveCity": "北京",
    "leaveCity": "广州",
    "flightNo": "HU7804",
    "onTimeRate": 100,
    "arrivePort": "首都国际机场",
    "arriveBuilding": "T2航站楼"
}
]


export const HOTEL_LINES = [{
    name: "轻住·西湖音乐喷泉公寓酒店",
    frequency: 146,
    compare: +3,
    lines: [
        { date: '周一', value: '104' },
        { date: '周二', value: '138' },
        { date: '周三', value: '132' },
        { date: '周四', value: '135' },
        { date: '周五', value: '125' },
        { date: '周六', value: '143' },
        { date: '周日', value: '146' },
    ]
},
{
    name: "轻住·杭州天逅酒店",
    frequency: 82,
    compare: -5,
    lines: [
        { date: '周一', value: '114' },
        { date: '周二', value: '148' },
        { date: '周三', value: '122' },
        { date: '周四', value: '115' },
        { date: '周五', value: '116' },
        { date: '周六', value: '87' },
        { date: '周日', value: '82' },
    ]
},
{
    name: "杭州途悦民宿东站店",
    frequency: 67,
    compare: +23,
    lines: [
        { date: '周一', value: '72' },
        { date: '周二', value: '57' },
        { date: '周三', value: '66' },
        { date: '周四', value: '76' },
        { date: '周五', value: '56' },
        { date: '周六', value: '44' },
        { date: '周日', value: '67' },
    ]
},
{
    name: "星程杭州钱江世纪城利华路酒店",
    frequency: 65,
    compare: +2,
    lines: [
        { date: '周一', value: '105' },
        { date: '周二', value: '120' },
        { date: '周三', value: '90' },
        { date: '周四', value: '81' },
        { date: '周五', value: '72' },
        { date: '周六', value: '63' },
        { date: '周日', value: '65' },
    ]
},
{
    name: "Zchic杭州美梦轻居酒店",
    frequency: 58,
    compare: -25,
    lines: [
        { date: '周一', value: '93' },
        { date: '周二', value: '100' },
        { date: '周三', value: '85' },
        { date: '周四', value: '87' },
        { date: '周五', value: '86' },
        { date: '周六', value: '83' },
        { date: '周日', value: '58' },
    ]
},
{
    name: "桔子杭州梦想小镇酒店",
    frequency: 56,
    compare: +2,
    lines: [
        { date: '周一', value: '61' },
        { date: '周二', value: '52' },
        { date: '周三', value: '38' },
        { date: '周四', value: '51' },
        { date: '周五', value: '52' },
        { date: '周六', value: '54' },
        { date: '周日', value: '56' },
    ]
},
{
    name: "全季杭州三墩西湖科技园酒店",
    frequency: 52,
    compare: +1,
    lines: [
        { date: '周一', value: '88' },
        { date: '周二', value: '122' },
        { date: '周三', value: '132' },
        { date: '周四', value: '70' },
        { date: '周五', value: '125' },
        { date: '周六', value: '51' },
        { date: '周日', value: '52' },
    ]
},
{
    name: "杭州钱江新城庆春广场亚朵酒店",
    frequency: 51,
    compare: +7,
    lines: [
        { date: '周一', value: '72' },
        { date: '周二', value: '55' },
        { date: '周三', value: '62' },
        { date: '周四', value: '52' },
        { date: '周五', value: '48' },
        { date: '周六', value: '44' },
        { date: '周日', value: '51' },
    ]
},
{
    name: "全季杭州转塘美院酒店",
    frequency: 49,
    compare: +12,
    lines: [
        { date: '周一', value: '73' },
        { date: '周二', value: '101' },
        { date: '周三', value: '25' },
        { date: '周四', value: '38' },
        { date: '周五', value: '62' },
        { date: '周六', value: '37' },
        { date: '周日', value: '49' },
    ]
},
{
    name: "美豪丽致酒店(杭州西溪湿地科技城店)",
    frequency: 45,
    compare: -5,
    lines: [
        { date: '周一', value: '98' },
        { date: '周二', value: '62' },
        { date: '周三', value: '46' },
        { date: '周四', value: '65' },
        { date: '周五', value: '52' },
        { date: '周六', value: '50' },
        { date: '周日', value: '45' },
    ]
}
]

export const NUMBER_TRIPS = [
    {
        name: '一周',
        data: {
            total: [102, 138, 126, 118, 105, 197, 188],
            scene: [47, 35, 22, 18, 49, 59, 51],
            hotel: [78, 77, 53, 64, 81, 99, 101],
            custom: [23, 25, 27, 23, 21, 32, 31],
            date: ['05-25', '05-26', '05-27', '05-28', '05-29', '05-30', '05-31']
        }
    },
    {
        name: '一个月',
        data: {
            total: [
                155,
                162,
                150,
                112,
                180,
                150,
                122,
                175,
                131,
                106,
                82,
                151,
                120,
                165,
                152,
                168,
                98,
                191,
                124,
                146,
                171,
                196,
                154,
                84,
                113,
                92,
                135,
                117,
                117,
                129,
                133
              ],
            scene: [
                33,
                30,
                56,
                64,
                64,
                61,
                49,
                67,
                45,
                50,
                17,
                59,
                51,
                68,
                15,
                68,
                26,
                57,
                41,
                62,
                31,
                15,
                19,
                66,
                18,
                31,
                20,
                51,
                56,
                42,
                22
              ],
            hotel: [
                71,
                50,
                55,
                90,
                81,
                92,
                51,
                52,
                64,
                85,
                61,
                62,
                63,
                91,
                77,
                97,
                99,
                95,
                58,
                63,
                80,
                73,
                76,
                51,
                81,
                71,
                70,
                88,
                83,
                57,
                59
              ],
            custom: [
                20,
                20,
                14,
                12,
                17,
                31,
                31,
                27,
                32,
                35,
                35,
                28,
                23,
                35,
                21,
                28,
                13,
                31,
                20,
                31,
                19,
                21,
                27,
                13,
                25,
                33,
                24,
                17,
                27,
                30,
                23
              ],
            date: [
                "05-01",
                "05-02",
                "05-03",
                "05-04",
                "05-05",
                "05-06",
                "05-07",
                "05-08",
                "05-09",
                "05-10",
                "05-11",
                "05-12",
                "05-13",
                "05-14",
                "05-15",
                "05-16",
                "05-17",
                "05-18",
                "05-19",
                "05-20",
                "05-21",
                "05-22",
                "05-23",
                "05-24",
                "05-25",
                "05-26",
                "05-27",
                "05-28",
                "05-29",
                "05-30",
                "05-31"
            ]
        }
    },
    {
        name: '一年',
        data: {
            total: [153, 138, 126, 118, 105, 197, 188],
            scene: [45, 35, 22, 18, 49, 59, 51],
            hotel: [78, 77, 53, 64, 81, 99, 101],
            custom: [23, 25, 27, 23, 21, 32, 31],
            date: ['2019-05', '2019-06', '2019-07', '2019-08', '2019-09', '2019-10', '2019-11', '2019-12', '2020-01', '2020-02', '2020-03', '2020-04', '2020-05']
        }
    }
]